### ISSUE TITLE
GltfModelBuilder create function take a long time

### ISSUE THREAD

**Issue by keainala** [javagl/JglTF#72] opened 2022-08-04 02:48 UTC
4hours not end

**Comment by javagl** [comment] 2022-08-04 14:20
The implementation of `GltfModelBuilder#create` is shown here:
```
    /**
     * Creates a new instance
     * 
     * @return The {@link GltfModelBuilder}
     */
    public static GltfModelBuilder create()
    {
        return new GltfModelBuilder();
    }
```
If this takes longer than a few microseconds, then something is wrong.

I assume that you refer to `GltfModelBuilder#build` method, which creates the actual model. That's where all the work happens, and where many things can go wrong. 

Maybe I should emphasize that the class is in an early state, as indicated by the hint in the README.md that says

> Note: This library is still subject to change.

The class has to be tested more extensively, and for different types of inputs and models. When you are doing that right now, then any feedback is appreciated, **iff** that feedback helps to improve the library.

However, the `build` method should not take a long time (although I have not yet made dedicated performance tests - I think that there is nothing that has a high algorithmic complexity). I also cannot imagine where it could run into some infinite loop or so. 

If you could insert the code that causes it to take a long time here, I could try to see what's wrong...
```
import de.javagl.jgltf.model.creation.GltfModelBuilder;
import de.javagl.jgltf.model.impl.DefaultGltfModel;

public class GltfModelBuilderIssue72
{
    public static void main(String[] args)
    {
        createGltf();
    }
    
    private static void createGltf()
    {
        System.out.println("Creating model DONE");

        GltfModelBuilder gltfModelBuilder = GltfModelBuilder.create();
        
        // Your code here...
        
        DefaultGltfModel gltfModel = gltfModelBuilder.build();

        System.out.println("Creating model DONE: " + gltfModel);
    }
}
```

**Comment by keainala** [comment] 2022-08-05 01:07
sorry  function  is build，

    public DefaultGltfModel build() {
        DefaultGltfModel gltfModel = new DefaultGltfModel();
        this.fill(gltfModel);
        return gltfModel;
    }

    private void fill(DefaultGltfModel gltfModel) {
        BufferBuilderStrategy bufferBuilderStrategy = new DefaultBufferBuilderStrategy();
        bufferBuilderStrategy.processMeshModels(this.meshModelsSet);    this line   take a long  time

**Comment by keainala** [comment] 2022-08-05 01:17
it is  build，   my code look like  GltfModelCreationExample  in project，  but it has about 200k   nodes，  when it has  2k nodes it  is well，

**Comment by javagl** [comment] 2022-08-05 17:07
This example adds approximately 1.4 million nodes, and takes approximatels 0.5 to do this:
```
package de.javagl.jgltf.model.creation.example;

import de.javagl.jgltf.model.creation.GltfModelBuilder;
import de.javagl.jgltf.model.impl.DefaultGltfModel;
import de.javagl.jgltf.model.impl.DefaultNodeModel;
import de.javagl.jgltf.model.impl.DefaultSceneModel;

public class GltfModelBuilderIssue72
{
    public static void main(String[] args)
    {
        createGltf();
    }
    
    private static void createGltf()
    {

        GltfModelBuilder gltfModelBuilder = GltfModelBuilder.create();
        
        System.out.println("Creating nodes");
        
        int depth = 10;
        int numChildren = 4;
        DefaultNodeModel nodeModel = createNode(depth, numChildren);
        
        System.out.println("Creating nodes DONE");
        
        long beforeNs = System.nanoTime();
        
        DefaultSceneModel sceneModel = new DefaultSceneModel();
        sceneModel.addNode(nodeModel);
        gltfModelBuilder.addSceneModel(sceneModel);
        
        DefaultGltfModel gltfModel = gltfModelBuilder.build();
        System.out.println("Creating model DONE: " + gltfModel);

        System.out.println(
            "Number of nodes: " + gltfModel.getNodeModels().size());
        
        long afterNs = System.nanoTime();
        double durationMs = (afterNs - beforeNs) / 1e9;
        System.out.println("Duration: " + durationMs + " ms");
    }
    
    private static DefaultNodeModel createNode(int depth, int numChildren)
    {
        DefaultNodeModel nodeModel = new DefaultNodeModel();
        if (depth > 0)
        {
            for (int i = 0; i < numChildren; i++)
            {
                DefaultNodeModel child = createNode(depth - 1, numChildren);
                nodeModel.addChild(child);
            }
        }
        return nodeModel;
    }
}
```
Of course, if each node has a mesh with primitives and materials and images, this will take longer. I don't want to make any further guesses about what you are doing.

But regardless of why it takes so long: Having 200k noes in a single asset sounds like a bad idea.

**Comment by keainala** [comment] 2022-08-08 05:25
yes， all nodes  have  mesh  ， I had test  combine 200k nodes  into one，the build method run  well， but the  mesh is not right 。when I use 2k nodes it all run well。how can I give datas  to you  only ，others can get it

**Comment by javagl** [comment] 2022-08-08 18:04
I verified this with this example that creates ~350000 nodes that contain meshes:
```
import java.nio.FloatBuffer;
import java.nio.IntBuffer;

import de.javagl.jgltf.model.creation.GltfModelBuilder;
import de.javagl.jgltf.model.creation.MaterialBuilder;
import de.javagl.jgltf.model.creation.MeshPrimitiveBuilder;
import de.javagl.jgltf.model.impl.DefaultGltfModel;
import de.javagl.jgltf.model.impl.DefaultMeshModel;
import de.javagl.jgltf.model.impl.DefaultMeshPrimitiveModel;
import de.javagl.jgltf.model.impl.DefaultNodeModel;
import de.javagl.jgltf.model.impl.DefaultSceneModel;
import de.javagl.jgltf.model.v2.MaterialModelV2;

public class GltfModelBuilderIssue72
{
    public static void main(String[] args)
    {
        createGltf();
    }
    
    private static void createGltf()
    {

        GltfModelBuilder gltfModelBuilder = GltfModelBuilder.create();
        
        System.out.println("Creating nodes");
        
        int depth = 9;
        int numChildren = 4;
        DefaultNodeModel nodeModel = createNode(depth, numChildren);
        
        System.out.println("Creating nodes DONE");
        
        long beforeNs = System.nanoTime();
        
        DefaultSceneModel sceneModel = new DefaultSceneModel();
        sceneModel.addNode(nodeModel);
        gltfModelBuilder.addSceneModel(sceneModel);
        
        DefaultGltfModel gltfModel = gltfModelBuilder.build();
        System.out.println("Creating model DONE: " + gltfModel);

        System.out.println(
            "Number of nodes: " + gltfModel.getNodeModels().size());
        
        long afterNs = System.nanoTime();
        double durationMs = (afterNs - beforeNs) / 1e6;
        System.out.println("Duration: " + durationMs + " ms");
    }
    
    private static DefaultNodeModel createNode(int depth, int numChildren)
    {
        DefaultNodeModel nodeModel = new DefaultNodeModel();
        if (depth > 0)
        {
            for (int i = 0; i < numChildren; i++)
            {
                DefaultNodeModel child = createNode(depth - 1, numChildren);
                nodeModel.addChild(child);
            }
        }
        nodeModel.addMeshModel(createMesh());
        return nodeModel;
    }
    
    private static DefaultMeshModel createMesh()
    {
        int indices[] = { 0, 1, 2 };
        float positions[] =
        {
            0.0f, 0.0f, 0.0f,
            1.0f, 0.0f, 0.0f,
            0.5f, 1.0f, 0.0f
        };
        
        MeshPrimitiveBuilder meshPrimitiveBuilder = 
            MeshPrimitiveBuilder.create(); 
        meshPrimitiveBuilder.setIntIndicesAsShort(IntBuffer.wrap(indices));
        meshPrimitiveBuilder.addPositions3D(FloatBuffer.wrap(positions));
        DefaultMeshPrimitiveModel meshPrimitiveModel = 
            meshPrimitiveBuilder.build();
        
        MaterialBuilder materialBuilder =  MaterialBuilder.create();
        materialBuilder.setBaseColorFactor(1.0f, 0.9f, 0.9f, 1.0f);
        materialBuilder.setDoubleSided(true);
        MaterialModelV2 materialModel = materialBuilder.build();
        meshPrimitiveModel.setMaterialModel(materialModel);

        DefaultMeshModel meshModel = new DefaultMeshModel();
        meshModel.addMeshPrimitiveModel(meshPrimitiveModel);
        
        return meshModel;
    }
}
```

And it did indeed take a long time to create this. 

The reason for that was a remarkably stupid way of generating "ID"s for the elements that are added. Or at least, a way that did not anticipate that there may be several hundred thousand meshes in one glTF. I still think that one should _not_ add so many nodes and meshes to one glTF, but that doesn't justify the implementation, which exposed _quadratic_ running time in the number of added elements. This is fixed via https://github.com/javagl/JglTF/commit/f53dec8aa5f0ce275eaea83b5bdeca22a3ed797e , and now, the above example prints
```
Creating nodes
Creating nodes DONE
Creating model DONE: de.javagl.jgltf.model.impl.DefaultGltfModel@7c16f3b
Number of nodes: 349525
Duration: 4710.6807 ms
```
thus creating the model in ~5 seconds.

This is part of version `2.0.3`, which has just been released. (Note that this release may not be 100% backward compatible, but ... should largely be). 

If this fixes the problem, this issue can be closed.

**Closed** 2022-08-11 01:28 UTC

**Comment by javagl** [comment] 2022-08-11 12:32
@keainala Good to see that the issue is resolved.

As I mentioned: The `GltfModelBuilder` and many related classes are still _preliminary_, and may change in the future. 

But if you are already using them, and if you find bugs, or unexpected behavior (like in this case), or when you think that a certain functionality should be added, then feel free to open an issue. (I can not promise anyhting, but I'd appreciate _any_ feedback here)

**Comment by keainala** [comment] 2022-08-15 08:25
@javagl  export  glb is the function  I need ，sometimes cant load big gltf file
